// Full 32-item MVP pool — 8 items per bin.
// Each item carries a teachingMessage shown on first-correct-sort (T12).
// labelDe / teachingMessageDe are the German translations.

const WASTE_ITEMS = [
  // ── General Waste ──────────────────────────────────────────────────────────
  {
    id: 'greasy-pizza-box',
    label: 'Greasy pizza box',
    labelDe: 'Fettiger Pizzakarton',
    emoji: '🍕',
    bin: 'general',
    material: 'mixed',
    teachingMessage: 'Food-soaked cardboard cannot go in paper recycling.',
    teachingMessageDe: 'Fettverschmierter Karton gehört nicht ins Papierrecycling.',
  },
  {
    id: 'used-tissue',
    label: 'Used tissue',
    labelDe: 'Benutztes Taschentuch',
    emoji: '🤧',
    bin: 'general',
    material: 'mixed',
    teachingMessage: 'Used tissues belong in general waste for this game.',
    teachingMessageDe: 'Benutzte Taschentücher gehören in den Restmüll.',
  },
  {
    id: 'crisp-packet',
    label: 'Crisp packet',
    labelDe: 'Chipstüte',
    emoji: '�',
    bin: 'general',
    material: 'mixed',
    teachingMessage: 'Crisp packets are mixed-material packaging, so they go in general waste.',
    teachingMessageDe: 'Chipstüten sind Verbundverpackungen und kommen in den Restmüll.',
  },
  {
    id: 'candy-wrapper',
    label: 'Candy wrapper',
    labelDe: 'Bonbonpapier',
    emoji: '🍬',
    bin: 'general',
    material: 'mixed',
    teachingMessage: 'Candy wrappers are not paper recycling in this game.',
    teachingMessageDe: 'Bonbonpapier gehört nicht ins Papierrecycling.',
  },
  {
    id: 'disposable-coffee-cup',
    label: 'Coffee cup',
    labelDe: 'Kaffeebecher',
    emoji: '☕',
    bin: 'general',
    material: 'mixed',
    teachingMessage: 'Disposable coffee cups have a plastic lining, so they go in general waste.',
    teachingMessageDe: 'Einwegkaffeebecher haben eine Kunststoffbeschichtung und kommen in den Restmüll.',
  },
  {
    id: 'broken-ceramic-mug',
    label: 'Broken mug',
    labelDe: 'Kaputte Tasse',
    emoji: '🫖',
    bin: 'general',
    material: 'ceramic',
    teachingMessage: 'Ceramics are not the same as recyclable glass.',
    teachingMessageDe: 'Keramik ist nicht dasselbe wie recycelbares Glas.',
  },
  {
    id: 'toothbrush',
    label: 'Toothbrush',
    labelDe: 'Zahnbürste',
    emoji: '🪥',
    bin: 'general',
    material: 'plastic',
    teachingMessage: 'Toothbrushes are too mixed and small for this recycling setup.',
    teachingMessageDe: 'Zahnbürsten sind zu gemischt und klein zum Recyceln.',
  },
  {
    id: 'sticky-tape',
    label: 'Sticky tape',
    labelDe: 'Klebeband',
    emoji: '🩹',
    bin: 'general',
    material: 'plastic',
    teachingMessage: 'Sticky tape cannot be recycled with clean paper.',
    teachingMessageDe: 'Klebeband kann nicht zusammen mit sauberem Papier recycelt werden.',
  },

  // ── Paper ──────────────────────────────────────────────────────────────────
  {
    id: 'newspaper',
    label: 'Newspaper',
    labelDe: 'Zeitung',
    emoji: '📰',
    bin: 'paper',
    material: 'paper',
    teachingMessage: 'Clean newspaper belongs in the paper bin.',
    teachingMessageDe: 'Saubere Zeitungen gehören in den Papiermüll.',
  },
  {
    id: 'magazine',
    label: 'Magazine',
    labelDe: 'Zeitschrift',
    emoji: '📖',
    bin: 'paper',
    material: 'paper',
    teachingMessage: 'Clean magazines can be recycled as paper in this game.',
    teachingMessageDe: 'Saubere Zeitschriften können als Papier recycelt werden.',
  },
  {
    id: 'mail-envelope',
    label: 'Mail envelope',
    labelDe: 'Briefumschlag',
    emoji: '✉️',
    bin: 'paper',
    material: 'paper',
    teachingMessage: 'Envelopes can go in paper recycling in this MVP.',
    teachingMessageDe: 'Briefumschläge können ins Papierrecycling.',
  },
  {
    id: 'cereal-box',
    label: 'Cereal box',
    labelDe: 'Müslischachtel',
    emoji: '🥣',
    bin: 'paper',
    material: 'paper',
    teachingMessage: 'Clean cardboard food boxes belong in paper recycling.',
    teachingMessageDe: 'Saubere Kartonverpackungen gehören ins Papierrecycling.',
  },
  {
    id: 'cardboard-box',
    label: 'Cardboard box',
    labelDe: 'Karton',
    emoji: '📦',
    bin: 'paper',
    material: 'paper',
    teachingMessage: 'Flattened cardboard boxes go in the paper bin.',
    teachingMessageDe: 'Flachgepresste Kartons kommen in den Papiermüll.',
  },
  {
    id: 'office-paper',
    label: 'Office paper',
    labelDe: 'Büropapier',
    emoji: '📄',
    bin: 'paper',
    material: 'paper',
    teachingMessage: 'Clean office paper is recyclable paper.',
    teachingMessageDe: 'Sauberes Büropapier gehört ins Papierrecycling.',
  },
  {
    id: 'paper-bag',
    label: 'Paper bag',
    labelDe: 'Papiertüte',
    emoji: '🛍️',
    bin: 'paper',
    material: 'paper',
    teachingMessage: 'Clean paper bags belong in paper recycling.',
    teachingMessageDe: 'Saubere Papiertüten gehören ins Papierrecycling.',
  },
  {
    id: 'egg-carton',
    label: 'Egg carton',
    labelDe: 'Eierkarton',
    emoji: '�',
    bin: 'paper',
    material: 'paper',
    teachingMessage: 'Cardboard egg cartons can go in the paper bin.',
    teachingMessageDe: 'Eierkartons aus Pappe kommen in den Papiermüll.',
  },

  // ── Plastic ────────────────────────────────────────────────────────────────
  {
    id: 'water-bottle',
    label: 'Water bottle',
    labelDe: 'Wasserflasche',
    emoji: '🫗',
    bin: 'plastic',
    material: 'plastic',
    teachingMessage: 'Plastic drink bottles belong in the plastic bin.',
    teachingMessageDe: 'Plastikflaschen gehören in den Plastikmüll.',
  },
  {
    id: 'milk-jug',
    label: 'Milk jug',
    labelDe: 'Milchflasche',
    emoji: '🥛',
    bin: 'plastic',
    material: 'plastic',
    teachingMessage: 'Milk jugs are recyclable plastic containers in this game.',
    teachingMessageDe: 'Milchflaschen sind recycelbare Kunststoffbehälter.',
  },
  {
    id: 'shampoo-bottle',
    label: 'Shampoo bottle',
    labelDe: 'Shampooflasche',
    emoji: '🧴',
    bin: 'plastic',
    material: 'plastic',
    teachingMessage: 'Empty shampoo bottles go in the plastic bin.',
    teachingMessageDe: 'Leere Shampooflaschen kommen in den Plastikmüll.',
  },
  {
    id: 'detergent-bottle',
    label: 'Detergent bottle',
    labelDe: 'Waschmittelflasche',
    emoji: '🫧',
    bin: 'plastic',
    material: 'plastic',
    teachingMessage: 'Household detergent bottles count as plastic recycling here.',
    teachingMessageDe: 'Waschmittelflaschen zählen hier als Plastikrecycling.',
  },
  {
    id: 'yogurt-pot',
    label: 'Yogurt pot',
    labelDe: 'Joghurtbecher',
    emoji: '🍮',
    bin: 'plastic',
    material: 'plastic',
    teachingMessage: 'Yogurt pots belong in the plastic bin in this game.',
    teachingMessageDe: 'Joghurtbecher gehören in den Plastikmüll.',
  },
  {
    id: 'margarine-tub',
    label: 'Margarine tub',
    labelDe: 'Margarinebehälter',
    emoji: '🧈',
    bin: 'plastic',
    material: 'plastic',
    teachingMessage: 'Margarine tubs are recyclable plastic in this game.',
    teachingMessageDe: 'Margarinebehälter sind recycelbarer Kunststoff.',
  },
  {
    id: 'fruit-punnet',
    label: 'Fruit punnet',
    labelDe: 'Obstschale',
    emoji: '🫐',
    bin: 'plastic',
    material: 'plastic',
    teachingMessage: 'Clear fruit punnets belong in the plastic bin.',
    teachingMessageDe: 'Klare Obstschalen gehören in den Plastikmüll.',
  },
  {
    id: 'bottle-cap',
    label: 'Bottle cap',
    labelDe: 'Flaschenverschluss',
    emoji: '🪙',
    bin: 'plastic',
    material: 'metal',
    teachingMessage: 'Bottle caps count as plastic recycling in this game.',
    teachingMessageDe: 'Flaschenverschlüsse zählen als Plastikrecycling.',
  },

  // ── Organic ────────────────────────────────────────────────────────────────
  {
    id: 'banana-peel',
    label: 'Banana peel',
    labelDe: 'Bananenschale',
    emoji: '🍌',
    bin: 'organic',
    material: 'organic',
    teachingMessage: 'Fruit scraps belong in organic waste.',
    teachingMessageDe: 'Obstabfälle gehören in den Biomüll.',
  },
  {
    id: 'apple-core',
    label: 'Apple core',
    labelDe: 'Apfelkerngehäuse',
    emoji: '🍎',
    bin: 'organic',
    material: 'organic',
    teachingMessage: 'Food scraps like apple cores go in organic waste.',
    teachingMessageDe: 'Speisereste wie Apfelkerngehäuse kommen in den Biomüll.',
  },
  {
    id: 'eggshells',
    label: 'Eggshells',
    labelDe: 'Eierschalen',
    emoji: '🥚',
    bin: 'organic',
    material: 'organic',
    teachingMessage: 'Eggshells belong in the organic bin.',
    teachingMessageDe: 'Eierschalen gehören in den Biomüll.',
  },
  {
    id: 'coffee-grounds',
    label: 'Coffee grounds',
    labelDe: 'Kaffeesatz',
    emoji: '🫘',
    bin: 'organic',
    material: 'organic',
    teachingMessage: 'Coffee grounds are organic waste.',
    teachingMessageDe: 'Kaffeesatz ist Biomüll.',
  },
  {
    id: 'tea-bag',
    label: 'Tea bag',
    labelDe: 'Teebeutel',
    emoji: '🍵',
    bin: 'organic',
    material: 'organic',
    teachingMessage: 'Compostable tea bags go in organic waste in this game.',
    teachingMessageDe: 'Kompostierbare Teebeutel kommen in den Biomüll.',
  },
  {
    id: 'bread-crust',
    label: 'Bread crust',
    labelDe: 'Brotrinde',
    emoji: '🍞',
    bin: 'organic',
    material: 'organic',
    teachingMessage: 'Old bread belongs in the organic bin.',
    teachingMessageDe: 'Altes Brot gehört in den Biomüll.',
  },
  {
    id: 'fish-bones',
    label: 'Fish bones',
    labelDe: 'Fischreste',
    emoji: '🐟',
    bin: 'organic',
    material: 'organic',
    teachingMessage: 'Fish scraps count as organic waste in this game.',
    teachingMessageDe: 'Fischreste zählen als Biomüll.',
  },
  {
    id: 'dead-flowers',
    label: 'Dead flowers',
    labelDe: 'Verwelkte Blumen',
    emoji: '🌸',
    bin: 'organic',
    material: 'organic',
    teachingMessage: 'Dead flowers and small plant waste go in organic waste.',
    teachingMessageDe: 'Verwelkte Blumen und Pflanzenabfälle kommen in den Biomüll.',
  },
]

export default WASTE_ITEMS
